export const stylesData = {
  page: {
    flexDirection: 'column',
    backgroundColor: '#ffffff',
    fontSize: 12,
    fontFamily: 'Poppins',
  },
  box: {
    width: 100,
    height: 3,
    backgroundColor: '#573089',
    marginBottom: 35,
  },
  center: {
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    border: '2px'
  },
  title: {
    fontSize: 25,
    fontWeight: '600',
    margin: 'auto',
    paddingBottom: 10,
    paddingTop: 8,
  },
  subtitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#6b7280',
    margin: 'auto',
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '600',
    marginTop: 30,
    marginBottom: 10,
  },
  dateTags: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    justifyContent: 'center',
    maxWidth: '450px',
  },
  publicHoliday: {
    fontSize: 10,
    marginBottom: '6',
    color: 'red',
    fontWeight: '600',
  },
  tag: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderRadius: 50,
    paddingHorizontal: 16,
    paddingVertical: 7,
    marginHorizontal: 8,
  },
  labels: {
    fontSize: 12,
    color: '#000',
    marginRight: 8,
    marginLeft: 8,
  },
  badge: {
    borderRadius: 20,
    paddingVertical: 3,
    paddingHorizontal: 8,
  },
  total: {
    borderWidth: 1,
    borderColor: '#3b82f6',
    marginLeft: '40px',
  },
  icon: {
    width: 12,
    height: 12
  },
  start: {
    borderWidth: 1,
    borderColor: '#10b981',
  },
  end: {
    borderWidth: 1,
    borderColor: '#fbbf24',
  },
  quoteBox: {
    backgroundColor: '#E5E9F8',
    padding: 24,
    borderRadius: 8,
    marginTop: 30,
    marginBottom: 30,
  },
  quoteText: {
    fontSize: 14,
    marginBottom: 10,
    marginTop: 10,
  },
  caption: {
    fontSize: 12,
    color: '#6b7280',
    margin: 'auto'
  },
  coma: {
    width: 14,
    height: 12
  },
  features: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 10,
  },
  featureBox: {
    alignItems: 'center',
    width: '33%',
  },
  featureTitle: {
    fontSize: 13,
    fontWeight: '600',
    marginTop: 10,
    marginBottom: 6,
  },
  featureDesc: {
    fontSize: 11,
    color: '#6b7280',
  },
  linkfooter: {
    backgroundColor: '#F9FAFB',
    padding: 24,
    marginTop: 24,
    borderRadius: 8,
  },
  footer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    fontSize: 12,
    textAlign: 'center',
    fontWeight: '600',
    color: '#6b7280',
    marginHorizontal: 'auto',
  },
  footersec: {
    fontSize: 12,
    textAlign: 'center',
    marginTop: 6,
    color: '#6b7280',
    marginHorizontal: 'auto',
  },
  footerlink: {
    fontSize: 12,
    textAlign: 'center',
    marginTop: 6,
    color: '#573089',
    textDecoration: 'underline',
    marginHorizontal: 'auto',
  },
  headerWrapper: {
    position: 'relative'
  },
  bar: {
    width: '100%',
    height: '65px',
  },
  footerbar: {
    width: '100%',
    height: '65px',
    transform: 'rotate(180deg)',
  },
  headerText: {
    position: 'absolute',
    top: 13,
    left: 25,
    color: '#ffffff',
    fontSize: 18,
    fontWeight: '600',
  },
  footerText: {
    position: 'absolute',
    top: 30,
    right: 25,
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '600',
  },
  logoCover: {
    borderRadius: '8px',
    backgroundColor: '#573089',
    overflow: 'hidden',
    borderWidth: 4,
    borderColor: '#573089'
  },
  logo: {
    width: 48,
    height: 48,
  },
  imgSection: {
    width: 32,
    height: 32,
  },
  badges: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F3F4F6',
    borderRadius: 20,
    paddingVertical: 3,
    paddingHorizontal: 8,
  },
  badgesText: {
    fontSize: 8,
    color: '#FFF',
    fontWeight: '600',
  },
  contentRow: {
    flexDirection: 'row',
    gap: 12,
  },
  leftColumn: {
    padding: 12,
    backgroundColor: '#F6F5FA',
    borderRadius: '10px',
    flex: 0.7,
    flexDirection: 'column',
    gap: 15,
  },
  rightColumn: {
    flex: 0.3,
    flexDirection: 'column',
    gap: 15,
    paddingRight: 10
  },
  dayTitle: {
    fontSize: 18,
    fontWeight: '600',
    marginBottom: 5,
    marginTop: 5,
    paddingLeft: 25,
    color: '#000',
  },
  dateText: {
    fontSize: 14,
    marginBottom: 15,
    paddingLeft: 25,
    color: '#555',
  },
  card: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 10,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 6,
  },
  cardHead: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  subject: {
    fontSize: 14,
    fontWeight: '600',
  },
  mainSubject: {
    fontSize: 11,
    fontWeight: '600',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    backgroundColor: '#f1f5f9',
    color: '#475569',
    textAlign: 'center',
  },
  badgeOptional: { backgroundColor: '#ddd6fe', color: '#5b21b6' },
  badgeCurrent: { backgroundColor: '#bbf7d0', color: '#15803d' },
  badgeDefault: { backgroundColor: '#f1f5f9', color: '#475569' },
  label: {
    fontSize: 10,
    color: '#64748b',
    marginTop: 4,
  },
  value: {
    textAlign: 'justify',
    fontSize: 11,
    marginBottom: 4,
    marginTop: 3,
  },
  widget: {
    backgroundColor: '#EFECF3',
    borderRadius: 12,
    padding: 15,
    borderWidth: 1,
    borderColor: '#e5e7eb',
  },
  widgetTitle: {
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 8,
  },
  widgetText: {
    fontSize: 11,
    color: '#64748b',
    lineHeight: 1.4,
    textAlign: 'justify'
  },
  footerWrapper: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    width: '100%',
    height: 60,
    overflow: 'hidden',
  },
  rightImg: {
    width: 30,
    height: 34,
    marginBottom: 8,
    objectFit: 'cover',
  }
}
